"""Qt application bootstrap: engine, controllers, QML loading.

Architecture note
-----------------
The QML shell is pure presentation. All vehicle state reaches it through
QObject controllers exposed as QML context properties (`Telemetry`, `Vehicle`,
`MapBridge`, `Mission`, `Video`). This keeps the door open to later replacing
any Python module with a Rust service without touching QML.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from PySide6.QtCore import QUrl, QTimer
from PySide6.QtGui import QGuiApplication, QFontDatabase
from PySide6.QtQml import QQmlApplicationEngine
# Import QtQuick Python bindings BEFORE engine.load: PySide6 registers wrapper
# types lazily per Python import. Without this, QML-created windows surface as
# generic QObject wrappers and isinstance(x, QQuickWindow) is False.
from PySide6.QtQuick import QQuickWindow, QQuickImageProvider  # noqa: F401

from app.bridge.appinfo import AppInfoController
from app.bridge.datalake import DataLakeController
from app.bridge.telemetry import TelemetryController
from app.bridge.vehicle import VehicleController
from app.bridge.mapbridge import MapController
from app.bridge.mission import MissionController
from app.video.controller import VideoController


def _load_token(engine: QQmlApplicationEngine, app_root: Path):
    """Create one Token instance from qml/theme/Token.qml and return it.

    Token.qml is generated by tools/gen_tokens.py from design/tokens.json.
    The returned object is parented to `engine` so it survives for the app
    lifetime and can be exposed as a QML context property.
    """
    from PySide6.QtQml import QQmlComponent
    tok = QQmlComponent(
        engine,
        str((app_root / "qml" / "theme" / "Token.qml").resolve()),
    )
    if tok.isError():
        for err in tok.errors():
            print(f"[token] ERROR: {err}", file=sys.stderr)
        print("FATAL: Token.qml failed to load", file=sys.stderr)
        return None
    obj = tok.create()
    if obj is None:
        print("FATAL: Token.qml created no object", file=sys.stderr)
        return None
    # Parent to the engine so the C++ object lives for the app lifetime
    # (QQmlComponent.create does not take a parent kwarg in this PySide6).
    obj.setParent(engine)
    return obj


def _load_bundled_fonts(app_root: Path) -> None:
    """Register the design-system fonts (tokens.json familyUi/familyMono) so
    the HUD renders identically on machines without them installed; absent
    files simply leave the system fallback in place."""
    fonts_dir = app_root / "assets" / "fonts"
    if not fonts_dir.is_dir():
        return
    for ttf in sorted(fonts_dir.glob("*.ttf")):
        if QFontDatabase.addApplicationFont(str(ttf)) < 0:
            print(f"[fonts] failed to load {ttf.name}", file=sys.stderr)


def run(app_root: Path, smoke: bool = False, driver=None) -> int:
    """Boot the app. `driver(root, app, controllers)` — if given — is called
    right after QML load (before exec) and may schedule timers, drive the UI
    and call app.quit(); used by tools/record_demo.py."""
    # Custom-styled Controls (Popup/TextField backgrounds) need the Basic style;
    # native styles ignore the customization and draw light-themed popups.
    os.environ.setdefault("QT_QUICK_CONTROLS_STYLE", "Basic")
    app = QGuiApplication(sys.argv)
    app.setApplicationName("Ghost Controller")
    app.setApplicationDisplayName("Ghost Controller")
    app.setOrganizationName("Ghost Handler")

    _load_bundled_fonts(app_root)

    engine = QQmlApplicationEngine()

    # NOTE: keep Python references alive — the QML engine does not take
    # ownership of context objects; without these locals the controllers are
    # garbage-collected and QML sees `null`.
    app_info = AppInfoController()

    # Token is the design-system singleton (colors / spacing / typography /
    # motion / opacity) consumed by every QML file as `Token.color.ui.text`,
    # `Token.typography.familyMono`, etc. Expose a single instance as a
    # context property so the bindings resolve identically from every import
    # context — a QQmlComponent-created instance is more reliable across the
    # onedir/AppImage extraction tree than a qmldir-registered singleton.
    _token_obj = _load_token(engine, app_root)
    engine.rootContext().setContextProperty("Token", _token_obj)
    lake = DataLakeController()
    telemetry = TelemetryController(data_lake=lake)

    from app.bridge.backend import build_source

    from app.bridge.link import apply_at_startup

    src, reason = build_source(pre_start=apply_at_startup)
    runtime = getattr(src, "_runtime", None)
    if src is not None:
        telemetry.attach_source(src)
    print(f"[telemetry] source={getattr(src, 'name', 'disconnected')} ({reason or 'in-process backend runtime'})")

    # Backend "alert" events (state/health workers) surface in the HUD alert
    # stream with a 10 s TTL — they are one-shot conditions, not latched state.
    if runtime is not None:
        def _route_alerts(event: dict) -> None:
            etype = event.get("type")
            if etype == "alert":
                telemetry._push_backend_alert(
                    str(event.get("level", "warn")), str(event.get("message", "")))
            elif etype == "health" and hasattr(src, "on_backend_event"):
                # BackendRuntimeSource keeps the latest health snapshot for
                # the HUD's ready/reason pill (web useHealthStore parity).
                src.on_backend_event(event)

        runtime.subscribe(_route_alerts)

    from app.bridge.battery import BatteryController
    battery = BatteryController(runtime)
    telemetry.set_battery(battery)
    vehicle = VehicleController(runtime)
    map_bridge = MapController()
    mission = MissionController(runtime)
    video = VideoController(data_lake=lake)
    from app.bridge.link import LinkController
    from app.bridge.params import ParamController
    link = LinkController(runtime)
    params = ParamController(runtime)
    engine.rootContext().setContextProperty("AppInfo", app_info)
    engine.rootContext().setContextProperty("Telemetry", telemetry)
    engine.rootContext().setContextProperty("Vehicle", vehicle)
    engine.rootContext().setContextProperty("Battery", battery)
    engine.rootContext().setContextProperty("MapBridge", map_bridge)
    engine.rootContext().setContextProperty("Mission", mission)
    engine.rootContext().setContextProperty("Video", video)
    engine.rootContext().setContextProperty("DataLake", lake)
    engine.rootContext().setContextProperty("Link", link)
    engine.rootContext().setContextProperty("Params", params)
    # NOTE: no image://map provider any more — tiles load as file:// URLs
    # (MapBridge.tileUrl). A Python image provider runs on Qt's pixmap-reader
    # thread and could deadlock against Python on the GUI thread.
    engine.addImageProvider("video", video.provider())

    # Vehicle position seeds the planner's home marker (H) ONCE per link —
    # re-latching it every tick (previous behavior) made home follow the
    # flying vehicle, so the H marker drifted across the planner map and
    # "home" moved while panning.
    _home_latched = {"armed_for": False}

    def _sync_home() -> None:
        frame = telemetry.telemetry
        connected = bool(frame.get("connected"))
        if not connected:
            _home_latched["armed_for"] = False  # re-latch on next link
            return
        if _home_latched["armed_for"]:
            return
        if frame.get("lat") is not None and frame.get("lon") is not None:
            mission.set_home(frame["lat"], frame["lon"])
            _home_latched["armed_for"] = True

    telemetry.telemetryChanged.connect(_sync_home)

    qml_main = app_root / "qml" / "Main.qml"
    engine.load(QUrl.fromLocalFile(str(qml_main)))
    if not engine.rootObjects():
        print("FATAL: QML failed to load", file=sys.stderr)
        return 1

    telemetry.start()

    if driver is not None:
        driver(engine.rootObjects()[0], app, {
            "lake": lake, "telemetry": telemetry, "map": map_bridge,
            "video": video, "mission": mission, "battery": battery,
            "link": link, "params": params, "runtime": runtime,
        })

    gh_smoke_view = os.environ.get("GH_SMOKE_VIEW", "")
    if smoke:
        root = engine.rootObjects()[0]
        # GH_SMOKE_VIDEO=1 opens the video source panel before the grab so
        # the panel is covered by the headless boot test.
        if os.environ.get("GH_SMOKE_VIDEO"):
            root.setProperty("videoOpen", True)
        # GH_SMOKE_VIEW=flight|map|planner boots into that view for the grab.
        if gh_smoke_view in ("flight", "map", "planner"):
            root.setProperty("viewMode", gh_smoke_view)
        result = {"ok": False}

        def finish() -> None:
            window = root if isinstance(root, QQuickWindow) else root.findChild(QQuickWindow)
            if window is not None:
                img = window.grabWindow()
                # Prefer app_root/build (writable in dev/venv). Inside an AppImage the
                # bundle is mounted read-only, so fall back to a writable location so the
                # smoke can still confirm the built artifact renders correctly.
                out = app_root / "build"
                smoke_path = out / "smoke.png"
                try:
                    out.mkdir(exist_ok=True)
                except OSError:
                    smoke_path = Path("/tmp") / "ghost-handler-smoke.png"
                ok = img.save(str(smoke_path))
                print(f"SMOKE: window title={window.title()!r} image={img.width()}x{img.height()} saved={ok} -> {smoke_path}")
                result["ok"] = bool(ok) and img.width() > 0
            else:
                print("SMOKE: no QQuickWindow found", file=sys.stderr)
            print("SMOKE_OK" if result["ok"] else "SMOKE_FAIL")
            app.exit(0 if result["ok"] else 1)

        QTimer.singleShot(1500, finish)

    rc = app.exec()
    mission.flush()          # persist a pending debounced save
    if runtime is not None:
        runtime.stop()       # close the MAVLink transport cleanly
    # Destroy the QML engine while the controllers are still alive, so QML
    # bindings never re-evaluate against released Python objects at shutdown.
    del engine
    video.shutdown()
    return rc
