#!/usr/bin/env python3
"""Generate UI artifacts from design/tokens.json — the single source of truth.

Outputs:
    qml/theme/Token.qml            FLAT QML QtObject: every leaf is a
                                   top-level readonly property with a dotted
                                   name like `color_ui_text`, `typography_size_md`.
                                   This keeps bindings reliable when Token is
                                   exposed as a QML context property.
    web/tokens/ghost-tokens.css    CSS custom properties (--gh-*)
    web/tokens/tailwind.ghost.json Tailwind v3 theme.extend fragment

The same tokens.json is consumed by the Figma plugin (design/figma-plugin),
keeping Figma, QML and the web HUD in lockstep. Run after any token change:

    python tools/gen_tokens.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
QML_OUT = ROOT / "qml" / "theme" / "Token.qml"
CSS_OUT = ROOT / "web" / "tokens" / "ghost-tokens.css"
TW_OUT = ROOT / "web" / "tokens" / "tailwind.ghost.json"


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def qml_type(value) -> str:
    if isinstance(value, str) and value.startswith("#"):
        return "color"
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, (int, float)):
        return "real"
    return "string"


def qml_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value)


def collect_leaves(nodes: dict, prefix: str, out: list[tuple[str, str, str]]):
    """Flatten a nested dict into (property_name, qml_type, qml_literal)."""
    for key, value in nodes.items():
        name = f"{prefix}_{key}" if prefix else key
        if isinstance(value, dict):
            collect_leaves(value, name, out)
        else:
            out.append((name, qml_type(value), qml_literal(value)))


def emit_qml_flat(leaves: list[tuple[str, str, str]], indent: int) -> list[str]:
    pad = " " * indent
    lines: list[str] = []
    for name, typ, lit in leaves:
        lines.append(f"{pad}readonly property {typ} {name}: {lit}")
    return lines


def emit_css(nodes: dict, prefix: str) -> list[str]:
    lines: list[str] = []
    for key, value in nodes.items():
        name = f"{prefix}-{kebab(key)}"
        if isinstance(value, dict):
            lines.extend(emit_css(value, name))
        else:
            lines.append(f"  --{name}: {value};")
    return lines


def emit_tailwind(nodes: dict) -> dict:
    out: dict = {}
    for key, value in nodes.items():
        out[key] = emit_tailwind(value) if isinstance(value, dict) else value
    return out


def main() -> int:
    if not TOKENS.exists():
        print(f"error: {TOKENS} not found — run from the repo root", file=sys.stderr)
        return 1
    data = json.loads(TOKENS.read_text())
    groups = {k: v for k, v in data.items() if k != "meta"}

    # --- QML: FLAT QtObject, one readonly property per leaf ---------------
    leaves: list[tuple[str, str, str]] = []
    collect_leaves(groups, "", leaves)

    qml = [
        "// GENERATED by tools/gen_tokens.py from design/tokens.json — do not edit.",
        "import QtQuick",
        "",
        "QtObject {",
    ]
    qml.extend(emit_qml_flat(leaves, 4))
    qml.append("}")
    qml.append("")

    QML_OUT.parent.mkdir(parents=True, exist_ok=True)
    QML_OUT.write_text("\n".join(qml))

    # qmldir (kept for backward compat; the desktop build now exposes Token as
    # a context property, but the file is still registered in case any tooling
    # or future QML import path relies on it).
    qmldir = QML_OUT.parent / "qmldir"
    if not qmldir.exists() or "Token.qml" not in qmldir.read_text():
        qmldir.write_text("singleton Token 1.0 Token.qml\n")

    # --- CSS -------------------------------------------------------------
    css = [
        "/* GENERATED by tools/gen_tokens.py from design/tokens.json — do not edit. */",
        ":root {",
        *emit_css(groups, "gh"),
        "}",
        "",
    ]
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text("\n".join(css))

    # --- Tailwind --------------------------------------------------------
    TW_OUT.parent.mkdir(parents=True, exist_ok=True)
    TW_OUT.write_text(json.dumps({"theme": {"extend": emit_tailwind(groups)}}, indent=2) + "\n")

    print(f"tokens: {len(leaves)} leaves -> {QML_OUT.relative_to(ROOT)}, "
          f"{CSS_OUT.relative_to(ROOT)}, {TW_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
